import PDFDocument from 'pdfkit';

export const PDF_COLORS = {
  background: '#F7F0E1',
  primary: '#1E1A14',
  onPrimary: '#F7F0E1',
  accent: '#D6C7A8',
  secondary: '#4A4133',
  muted: '#6B5F4B',
  border: '#D6C7A8',
  zebra: '#EFE5D0',
  breach: '#A81F2D',
  safe: '#106349',
};

export const PAGE = {
  margin: 50,
  width: 595.28,
  height: 841.89,
  contentWidth: 495,
  bottom: 760,
};

export function newDocument(): PDFKit.PDFDocument {
  return new PDFDocument({ size: 'A4', margin: PAGE.margin, bufferPages: true });
}

export function paintBackground(doc: PDFKit.PDFDocument) {
  doc.rect(0, 0, doc.page.width, doc.page.height).fill(PDF_COLORS.background);
}

export function drawHeader(doc: PDFKit.PDFDocument, title: string, subtitle?: string) {
  doc.rect(0, 0, doc.page.width, 90).fill(PDF_COLORS.primary);
  doc.fillColor(PDF_COLORS.onPrimary).fontSize(20).text(title, PAGE.margin, 30, {
    width: PAGE.contentWidth,
  });

  if (subtitle) {
    doc.fontSize(10).fillColor(PDF_COLORS.accent).text(subtitle, PAGE.margin, 60, {
      width: PAGE.contentWidth,
    });
  }

  return 120;
}

export function drawFooter(doc: PDFKit.PDFDocument, note?: string) {
  doc.fillColor(PDF_COLORS.muted).fontSize(8).text(
    note || 'Generated by Procurix on ' + new Date().toLocaleString('en-IN'),
    PAGE.margin,
    doc.page.height - 50,
    { width: PAGE.contentWidth, align: 'center' }
  );
}

export function drawSectionTitle(doc: PDFKit.PDFDocument, text: string, y: number): number {
  doc.rect(PAGE.margin, y, 3, 14).fill(PDF_COLORS.primary);
  doc.fillColor(PDF_COLORS.primary).fontSize(12).text(text, PAGE.margin + 10, y, {
    width: PAGE.contentWidth - 10,
  });
  return y + 24;
}

export function drawKeyValues(
  doc: PDFKit.PDFDocument,
  pairs: Array<[string, string]>,
  y: number
): number {
  const columnWidth = PAGE.contentWidth / 2;

  pairs.forEach(([label, value], i) => {
    const column = i % 2;
    const rowY = y + Math.floor(i / 2) * 38;
    const x = PAGE.margin + column * columnWidth;

    doc.fillColor(PDF_COLORS.secondary).fontSize(8).text(label.toUpperCase(), x, rowY, {
      width: columnWidth - 12,
    });
    doc.fillColor(PDF_COLORS.primary).fontSize(13).text(value, x, rowY + 12, {
      width: columnWidth - 12,
    });
  });

  return y + Math.ceil(pairs.length / 2) * 38 + 8;
}

export interface TableColumn {
  header: string;
  width: number;
  align?: 'left' | 'right';
}

export function drawTable(
  doc: PDFKit.PDFDocument,
  columns: TableColumn[],
  rows: string[][],
  startY: number,
  onNewPage?: (doc: PDFKit.PDFDocument) => number
): number {
  let y = startY;

  const drawHeadings = () => {
    doc.rect(PAGE.margin, y, PAGE.contentWidth, 20).fill(PDF_COLORS.primary);
    doc.fillColor(PDF_COLORS.onPrimary).fontSize(8);
    let x = PAGE.margin + 8;
    for (const column of columns) {
      doc.text(column.header.toUpperCase(), x, y + 6, {
        width: column.width - 8,
        align: column.align || 'left',
      });
      x += column.width;
    }
    y += 20;
  };

  drawHeadings();

  rows.forEach((row, index) => {
    const height = 22;

    if (y + height > PAGE.bottom) {
      doc.addPage();
      paintBackground(doc);
      y = onNewPage ? onNewPage(doc) : PAGE.margin;
      drawHeadings();
    }

    if (index % 2 === 0) {
      doc.rect(PAGE.margin, y, PAGE.contentWidth, height).fill(PDF_COLORS.zebra);
    }

    doc.fillColor(PDF_COLORS.primary).fontSize(8);
    let x = PAGE.margin + 8;
    row.forEach((cell, i) => {
      const column = columns[i];
      doc.text(cell ?? '', x, y + 7, {
        width: column.width - 8,
        align: column.align || 'left',
        ellipsis: true,
        height: 10,
      });
      x += column.width;
    });

    y += height;
  });

  return y + 10;
}

export function toBuffer(doc: PDFKit.PDFDocument): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    doc.end();
  });
}

export function csvEscape(value: unknown): string {
  const text = value === null || value === undefined ? '' : String(value);
  return /[",\n]/.test(text) ? '"' + text.replace(/"/g, '""') + '"' : text;
}

export function toCsv(headers: string[], rows: Array<Array<unknown>>): string {
  const lines = [headers.map(csvEscape).join(',')];
  for (const row of rows) lines.push(row.map(csvEscape).join(','));
  return lines.join('\r\n');
}
